ETL/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('etl_app.urls'))
]

etl_app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.login, name='login'),
    path('home/', views.home, name='home'),
    path('logout/', views.logout, name='logout'),
    path('cargar_pendientes/', views.cargar_pendientes, name='cargar_pendientes'),
    path('procesar_fichero/', views.procesar_fichero, name='procesar_fichero'),
    path('admin_page/', views.admin_page, name='admin_page')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

etl_app/models.py
from django.db import models

# Create your models here.

etl_app/forms.py
from django import forms

class AdministradorForm(forms.Form):
    nombre = forms.CharField(max_length=50, label="Nombre")
    siglas = forms.CharField(max_length=10, label="Siglas")

etl_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse,  JsonResponse
from .etl import main
from django.contrib import messages
from django.db import connection
from django.conf import settings
from django.contrib.auth.decorators import login_required
import os
from .forms import AdministradorForm

ruta_archivo_config = 'etl_app/etl/configs/config.yaml'

def login(request):
    if request.session['is_authenticated']:  # Verificar si el usuario ya inició sesión
        return redirect('home')  # Redirigir al "home"
    
    error_message = ""

    if request.method == 'POST':
        # Obtener datos del formulario
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Comprueba que los campos estén rellenos
        if not username or not password:
            error_message = "Por favor, ingresa tu usuario y contraseña."
        else:
            # Consulta para verificar usuario
            with connection.cursor() as cursor:
                cursor.execute("SELECT * FROM Usuario WHERE username = %s", [username])
                usuario = cursor.fetchone()

            if usuario:
                # usuario[4] tiene almacenada la contraseña del usuario
                db_password = usuario[4]
                if db_password == password:
                    # Guardar los datos del usuario en la sesión
                    request.session['usuario_id'] = usuario[0] # usuario[0] tiene almacenado el id del usuario
                    request.session['username'] = usuario[3] # usuario[3] tiene almacenado el username del usuario
                    request.session['is_authenticated'] = True
                    return redirect('home')
                else:
                    error_message = "La contraseña ingresada es incorrecta."
            else:
                error_message = "El usuario ingresado no existe."

    return render(request, 'login.html', {'error_message': error_message})

def logout(request):
    # Eliminar las claves de sesión personalizadas
    request.session['usuario_id'] = None
    request.session['username'] = None
    request.session['is_authenticated'] = False
    messages.success(request, 'Has cerrado sesión correctamente.')
    
    # Redirigir a la página de login
    return redirect('login')

# Vista para el home
def home(request):
    if not request.session.get('is_authenticated', False):
        messages.warning(request, 'Debes iniciar sesión para acceder a esta página.')
        return redirect('login')
    
    datos = main.get_tipo_datos()
    return render(request, 'home.html', {'datos': datos})

def cargar_pendientes(request):
    id_tipo_dato = request.GET.get('id_tipo_dato')
    if id_tipo_dato:
        ficheros = main.get_ficheros_pendientes(id_tipo_dato)
        return JsonResponse(ficheros, safe = False)
    
    messages.error(request, 'Tipo de dato no válido.')
    return redirect('home')

def procesar_fichero(request):
    if request.method == 'POST':
        id_tipo_dato = request.POST.get('tipo_dato')  # Obtener el tipo de dato
        id_fichero = request.POST.get('ficheros')
        
        # Consulta directa a la base de datos
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM Fichero WHERE id = %s", [id_fichero])
            fichero = cursor.fetchone()  # Devuelve None si no encuentra resultados
            
        with connection.cursor() as cursor:
            cursor.execute("SELECT * FROM TipoDato WHERE id = %s", [id_tipo_dato])
            tipo_dato = cursor.fetchone()  # Devuelve None si no encuentra resultados

        if not fichero or not tipo_dato:
            messages.error(request, 'No se encontró el fichero o el tipo de dato.')
            return redirect('home')
        
        # Definir la ruta para buscar el archivo
        fichero_path = os.path.join(settings.MEDIA_ROOT, 'ficheros', tipo_dato[1], fichero[5])
        
        # Verificar si el fichero realmente existe en la ruta
        if not os.path.exists(fichero_path):
            return JsonResponse({'status': 'error', 'message': 'No se ha podido encontrar el archivo.'})
        
        idUsuario = request.session['usuario_id']
        
        if main.cargar_fichero(fichero_path):
            main.update_fichero(idUsuario, fichero_path, id_fichero)
            return JsonResponse({'status': 'success', 'message': 'Fichero procesado exitosamente.'})
        else:
            return JsonResponse({'status': 'error', 'message': 'Error al procesar el fichero.'})

    return JsonResponse({'status': 'error', 'message': 'No se ha enviado ningún fichero.'})

def admin_page(request):
    # Verificar si el usuario está autenticado
    if not request.session.get('is_authenticated', False):
        messages.error(request, 'Debes iniciar sesión para acceder a esta página.')
        return redirect('login')
    
    # Verificar si el usuario tiene permisos de administrador
    if request.session.get('username') != "admin":
        messages.error(request, 'No tienes permiso para acceder a esta página.')
        return redirect('home')

    if request.method == 'POST':
        form = AdministradorForm(request.POST)
        # Verificar si el formulario es válido
        if form.is_valid():
            # Obtener los datos del formulario
            nombre = form.cleaned_data['nombre']
            siglas = form.cleaned_data['siglas']
            
            # Llamar a la función para insertar el tipo de dato
            resultado = main.insertar_tipo_dato(nombre, siglas)
            
            # Responder con un mensaje indicando que el formulario fue enviado correctamente
            return render(request, 'admin_page.html', {'form': form, 'resultado': resultado})
    else:
        form = AdministradorForm()

    return render(request, 'admin_page.html', {'form': form})

etl_app/templates/admin_page.html
{% extends 'base.html' %}

{% block title %}Administración{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="card shadow" style="width: 400px;">
        <div class="card-body">
            </br>
            <h5 class="card-title text-center">Añadir tipo de dato a la aplicación</h5>
            </br>
            <form method="post">
                {% csrf_token %}
                
                <!-- Campo Nombre -->
                <div class="mb-3">
                    <label for="id_nombre" class="form-label">Nombre del tipo de dato:</label>
                    <input type="text" name="nombre" id="id_nombre" class="form-control" value="">
                    {% if form.nombre.errors %}
                        <div class="alert alert-danger mt-2">
                            <strong>Error:</strong> {{ "Rellena el nombre del tipo de dato" }}
                        </div>
                    {% endif %}
                </div>
                
                <!-- Campo Siglas -->
                <div class="mb-3">
                    <label for="id_siglas" class="form-label">Siglas del tipo de dato:</label>
                    <input type="text" name="siglas" id="id_siglas" class="form-control" value="">
                    {% if form.siglas.errors %}
                        <div class="alert alert-danger mt-2">
                            <strong>Error:</strong> {{ "Rellena las siglas del tipo de dato" }}
                        </div>
                    {% endif %}
                </div>

                <!-- Botón de Enviar -->
                <button type="submit" class="btn btn-primary w-100">Enviar</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

etl_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}ETL AMAT{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<!-- Encabezado -->
<header class="bg-primary text-white">
    <div class="container d-flex justify-content-between align-items-center py-3">
        
        <img src="{% static 'img/Logo_amat_negativo.png' %}" alt="Logo" style="height: 50px;">

        <nav>
            <!-- Si el usuario está autenticado -->
            {% if request.session.is_authenticated %}
                {% if request.session.username == "admin" %}
                    <a href="{% url 'admin_page' %}" class="text-white mx-2">Panel de Administrador</a>
                {% endif %}
                <a href="{% url 'home' %}" class="text-white mx-2">Procesar ficheros</a>
                <a href="{% url 'logout' %}" class="text-white mx-2">Cerrar Sesión</a>
            {% else %}
                <!-- Si el usuario no está autenticado -->
                <a href="{% url 'login' %}" class="text-white mx-2">Iniciar sesión</a>
            {% endif %}
        </nav>
    </div>
</header>
    
    {% block content %}{% endblock %}

    <footer>
        
    </footer>

    <!-- Enlace a los scripts de Bootstrap -->
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="{% static 'js/cargar_pendientes.js' %}"></script>
    <script src="{% static 'js/utils.js' %}"></script>
    {% if messages %}
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            {% for message in messages %}
                // Solo genera el alert si hay contenido
                if ("{{ message }}" !== "") {
                    alert("{{ message|escapejs }}");
                }
            {% endfor %}
        });
    </script>
    {% endif %}
</body>
</html>

etl_app/templates/home.html
{% extends 'base.html' %}

{% block title %}ETL AMAT{% endblock %}

{% block content %}
<div class="container mt-5">
    <form id="tipo_dato_form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="select-container">
            <div class="tipo_dato_container mb-3">
                <label for="tipo_dato" class="form-label">Seleccione un tipo de dato: </label>
                <select id="tipo_dato" name="tipo_dato" class="form-select">
                    <option value="" selected>Seleccione un tipo de dato</option>
                    {% for dato in datos %}
                        <option value="{{ dato.id }}">{{ dato.nombre }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="ficheros_pendientes_container mb-3">
                <label for="id_fichero" class="form-label">Lista de ficheros pendientes:</label>
                <select id="ficheros" name="ficheros" class="form-select">
                    <option value="">Seleccione un fichero</option>
                </select>    
            </div> 
        </div>

        <!-- Botón para enviar los ficheros seleccionados -->
        <div class="boton_procesar">
            <button type="submit" id="enviar_btn" class="btn btn-primary">Procesar</button>
        </div>  
    </form>
</div>

<!-- Popup de carga -->
<div id="popupCarga" style="display: none;">
    <div class="spinner-border" role="status">
        <span class="visually-hidden">Cargando...</span>
    </div>
    Procesando el fichero, por favor espere...
</div>
<script type="text/javascript">
    var procesarFicheroUrl = "{% url 'procesar_fichero' %}";
</script>

{% endblock %}

etl_app/templates/login.html
{% extends 'base.html' %}

{% block title %}Iniciar sesión{% endblock %}

{% block content %}
<div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="card shadow" style="width: 400px;">
        <div class="card-body">
            <h5 class="card-title text-center">Inicio sesión AMAT</h5>
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_username" class="form-label">Nombre de usuario</label>
                    <input type="text" name="username" id="id_username" class="form-control" value="">
                </div>
                <div class="mb-3">
                    <label for="id_password" class="form-label">Contraseña</label>
                    <input type="password" name="password" id="id_password" class="form-control" value="">
                </div>
                <button type="submit" class="btn btn-primary w-100">Entrar</button>
            </form>

            <!-- Mostrar mensaje de error si existe -->
            {% if error_message %}
                <div class="alert alert-danger mt-3">
                    <strong>Error:</strong> {{ error_message }}
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}